### ISSUE TITLE
[Bug] - FPS reduction slider can lose its place (give inaccurate results) after sliding/skipping

### ISSUE THREAD

**Issue by CCpt5** [LonicaMewinsky/frame2frame#2]
Hey again, 

One minor UI issue I noticed playing around w/ "frame2frame" earlier. If you use the slider a bit in the same session (or slide, jump, slide, jump) it has a tendency to loses its place and come up with an inaccurate FPS value. I used OBS to cap a quick example (vid below). Minor, but wanted to mention. Thanks!

(am on the latest commit of both extension & a1111) / The MP4 in the sample was rendered out of Vegas at standard NTSC 29.97 fps 

https://user-images.githubusercontent.com/37972078/223905988-1bf4fd3a-9f74-4676-a42e-cb682755c675.mp4

**Comment by LonicaMewinsky** [comment]
Thanks. I was able to reproduce this by moving the slider back and forth repeatedly, quickly. When the slider is moved slowly (or up/down arrows are used), it seems to remain accurate. I'll see about options to prevent this.

**Comment by LonicaMewinsky** [comment]
I've stopped the real-time update and placed a button instead. This is a stopgap while I find a long-term solution (this is a UI limitation.) Thanks again.

**Comment by LonicaMewinsky** [comment]
Unfortunately, this problem is patched in a more recent release of Gradio (the UI), which A1111 is not using. This will need to remain a button for now. :(
