### ISSUE TITLE
[Bug] - Sometimes F2F breaks IMG2IMG even when it's not selected as a script - (Perhaps when a previously loaded video isn't closed before restart)

### ISSUE THREAD

**Issue by CCpt5** [LonicaMewinsky/frame2frame#4]
My IMG2IMG has been breaking w/ the below error sporadically for the past few days.  I hadn't narrowed it down to a specific extension as I just kept disabling a bunch and eventually it would resolve. However, I did narrow it does to F2F today as I'm getting the error below if it's enabled, but if I disable it and restart I don't get the error.

I -think- what's going is that if you close F2F w/o clicking the [x] on the video (and removing it) that can cause problems. What's bad is that this error occurs even if F2F isn't selected in the script box and after a restart of the whole webui. 

I've disabled F2F for now as I don't have a use for it and I know it's still a work in prog, but I definitely wanted to pass this along. If it's something related to my specific setup my apologies:

-----
Closing server running on port: 7860
Restarting UI...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 377.6s (import gradio: 0.9s, import ldm: 0.3s, other imports: 0.8s, list extensions: 0.4s, list SD models: 0.7s, load scripts: 0.7s, load SD checkpoint: 3.1s, scripts before_ui_callback: 361.6s, create ui: 8.6s, gradio launch: 0.3s, scripts app_started_callback: 0.2s).

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 540, in preprocess
    return self._round_to_precision(x, self.precision)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 502, in _round_to_precision
    return float(num)

ValueError: could not convert string to float: ''  

----

**Comment by LonicaMewinsky** [comment]
Thanks a bunch. I'll do my best to recreate this and resolve it.

**Comment by LonicaMewinsky** [comment]
@CCpt5 looks like this might be a webui/gradio bug, looking at https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/1225. There is a solution, being to remove the extension's entries from your ui-config.json.

I'm going to leave this open until I can reach more certainty that f2f _didn't cause_ it.

**Comment by LonicaMewinsky** [comment]
@CCpt5 I conferred with another author that ran into this issue, and unfortunately there wasn't much to go on. I added some additional checks to mitigate type mismatch, and going to close the issue for now. Thanks for the help here.
